In [1]:
from matplotlib import pyplot as plt
import random 
import torch
%matplotlib inline

In [2]:
def synthetic_data(w,b,num):
    X=torch.normal(0,1,(num,len(w)))
    y=torch.matmul(X,w)+b
    y+=torch.normal(0,0.01,y.shape)
    return X,y.reshape((-1,1))

In [3]:
true_w=torch.tensor([2,-3.4])
true_b=4.2
features,labels=synthetic_data(true_w,true_b,1000)
features[0],labels[0]

(tensor([ 0.5009, -0.7101]), tensor([7.5955]))

In [4]:
def data_iter(batch_size,features,labels):
    num=len(features)
    indices=list(range(num)) 
    random.shuffle(indices)# 随机打乱下标
    
    for i in range(0,num,batch_size):
        batch_indices=torch.tensor(indices[i:min(i+batch_size,num)])
        yield features[batch_indices],labels[batch_indices]
batch_size=10
for X,y in data_iter(batch_size,features,labels):
    pass
    #print(X,'\n',y)   


In [5]:
w=torch.normal(0,0.01,size=(2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)
#初始化数据

In [6]:
def linreg(X,w,b):
    return torch.matmul(X,w)+b

In [7]:
def loss(y_hat,y):
    return (y_hat-y.reshape(y_hat.shape))**2/2

In [8]:
def sgd(params,lr,batch_size):
    with torch.no_grad():
        for param in params:
            param[:]=param-lr*param.grad / batch_size
            param.grad.zero_()

In [26]:
lr=0.011
epochs=310
net=linreg
loss=loss

for epoch in range(epochs):
    for X,y in data_iter(batch_size,features,labels):
        l=loss(net(X,w,b),y)
    l.sum().backward()
    sgd([w,b],lr,batch_size)
    with torch.no_grad():
        train_l=loss(net(features,w,b),labels)
        print(f'epoch {epoch + 1},loss {float(train_l.mean()):f}')

epoch 1,loss 2.482023
epoch 2,loss 2.417161
epoch 3,loss 2.363870
epoch 4,loss 2.328424
epoch 5,loss 2.272088
epoch 6,loss 2.237897
epoch 7,loss 2.212868
epoch 8,loss 2.192723
epoch 9,loss 2.144315
epoch 10,loss 2.068364
epoch 11,loss 2.054491
epoch 12,loss 2.013029
epoch 13,loss 1.998718
epoch 14,loss 1.960526
epoch 15,loss 1.935178
epoch 16,loss 1.900162
epoch 17,loss 1.868725
epoch 18,loss 1.836167
epoch 19,loss 1.819399
epoch 20,loss 1.775590
epoch 21,loss 1.732140
epoch 22,loss 1.692877
epoch 23,loss 1.665347
epoch 24,loss 1.634808
epoch 25,loss 1.601601
epoch 26,loss 1.548776
epoch 27,loss 1.529487
epoch 28,loss 1.500742
epoch 29,loss 1.473498
epoch 30,loss 1.443659
epoch 31,loss 1.417822
epoch 32,loss 1.394843
epoch 33,loss 1.376989
epoch 34,loss 1.346783
epoch 35,loss 1.317343
epoch 36,loss 1.278838
epoch 37,loss 1.260164
epoch 38,loss 1.239101
epoch 39,loss 1.222743
epoch 40,loss 1.201122
epoch 41,loss 1.175722
epoch 42,loss 1.155617
epoch 43,loss 1.132504
epoch 44,loss 1.1074

In [21]:
true_w

tensor([ 2.0000, -3.4000])

In [27]:
w

tensor([[ 1.9630],
        [-3.3439]], requires_grad=True)